name: wky-armbian

on: 
  release:
    types: [published]

  #push:
  #  branches:
  #    - master:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Initialization environment
      run: |
        sudo -E apt-get update
        sudo -E apt-get -y install 
